import { Montserrat } from 'next/font/google'
import './globals.css'
import { ProviderNextUI } from './providers'
const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} h-screen`}>
				<ProviderNextUI>{children}</ProviderNextUI>
			</body>
		</html>
	)
}
